version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000" # don't require package comments
        - "-ST1001" # allow dot imports (ginkgo/gomega in e2e tests)
