apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cnpg-pg-doorman.labels" . | nindent 4 }}
  name: {{ include "cnpg-pg-doorman.fullname" . }}
  namespace: {{ .Release.Namespace }}
