apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - crd/pg-doorman.cnpg.io_pgdoormen.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - certificate-issuer.yaml
  - client-certificate.yaml
  - deployment.yaml
  - pdb.yaml
  - server-certificate.yaml
  - service.yaml
images:
  - name: pg-doorman-plugin
    newName: pg-doorman-plugin
    newTag: testing
secretGenerator:
  - name: pg-doorman
    literals:
      - SIDECAR_IMAGE=pg-doorman-wrapper:testing
    options:
      disableNameSuffixHash: true
