name: release-please

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  gate:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Run go vet
        run: go vet ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13.1
      - name: Run unit tests
        run: go test ./internal/... -race

  release-please:
    runs-on: ubuntu-latest
    needs: [gate]
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install node
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v4
      - name: Install Task
        uses: arduino/setup-task@v3.0.0
      - name: Install Dagger
        env:
          # renovate: datasource=github-tags depName=dagger/dagger versioning=semver
          DAGGER_VERSION: 0.21.9
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Create image and manifest
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          task publish
          task manifest
      - name: Attach manifest to workflow run
        uses: actions/upload-artifact@v7
        with:
          name: manifest.yaml
          path: ./manifest.yaml
      - name: Run release-please
        run: |
          npx release-please release-pr \
            --token="${{ secrets.REPO_PAT }}" \
            --repo-url="${{ github.repository }}"
          npx release-please github-release \
            --token="${{ secrets.REPO_PAT }}" \
            --repo-url="${{ github.repository }}"
